# Generated by Django 3.1.7 on 2021-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Enter your area code and mobile no., e.g. for HK mobile, +85291231234', max_length=15),
        ),
    ]
