# Generated by Django 3.1.7 on 2021-04-12 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('bought_quantity', models.IntegerField(default=0)),
                ('bought_unit_price', models.FloatField(default=0.0)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('sold_unit_price', models.FloatField(default=0.0)),
                ('long_position_before', models.IntegerField(default=0)),
                ('long_position_after', models.IntegerField(default=0)),
                ('short_position_before', models.IntegerField(default=0)),
                ('short_position_after', models.IntegerField(default=0)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('b', 'buy'), ('s', 'sell')], max_length=1, verbose_name='transaction type')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('tx_time', models.DateField(verbose_name='transction time')),
                ('fee', models.FloatField(null=True, verbose_name='transaction fee')),
                ('tax', models.FloatField(null=True, verbose_name='tax levied')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='trader.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
