# Generated by Django 3.1.7 on 2021-04-13 05:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0002_stockholdings_usercash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCash',
            new_name='Cash',
        ),
    ]
