# Generated by Django 3.1.7 on 2021-04-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_cash_stockholdings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHoldings',
        ),
    ]
