# Generated by Django 3.1.7 on 2021-04-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_auto_20210422_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtx',
            name='cash',
        ),
        migrations.AddField(
            model_name='cashtx',
            name='cash_after',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cashtx',
            name='cash_before',
            field=models.FloatField(default=0.0),
        ),
    ]
