# Generated by Django 3.1.7 on 2021-04-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_auto_20210422_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
    ]
