# Generated by Django 3.1.7 on 2021-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_remove_transaction_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(default='AAPL', max_length=10),
            preserve_default=False,
        ),
    ]
